version: "3.8"

services:
  go_mysql:
    image: mysql:8.0
    container_name: go_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3400:3306"
    volumes:
      - go_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "rest_gin"
      MYSQL_USER: "rest_gin"
      MYSQL_PASSWORD: "rest_gin"
      MYSQL_ROOT_PASSWORD: "rest_gin"

volumes:
  go_db:

#networks:
#  nt-mysql:
#    driver: bridge